services:
  backend:
    build: ./back-end
    container_name: notes-backend
    command: npm start
    restart: unless-stopped
    networks:
      - 2tier-app
    volumes:
      - ./back-end/src:/app/src
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./front-end
    container_name: notes-frontend
    # command: npm start  commenting this so nginx can start the frontend not npm
    restart: unless-stopped
    networks:
      - 2tier-app
    volumes:
      - ./front-end/src:/app/src
      - ./front-end/public:/app/public
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

  networks:
    2tier-app:
      driver: bridge  